# Generated by Django 6.0.2 on 2026-02-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_trope', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trope_name', models.CharField(max_length=100)),
                ('reflection_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
